(function(){
  const fallback=window.K2K_FALLBACK||{};const $=id=>document.getElementById(id);const text=(id,value)=>{if($(id))$(id).textContent=value};const fmt=value=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:1}).format(Number(value)||0);
  const menu=$('dashboardNav'),menuButton=document.querySelector('.dash-menu-button');menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menu.classList.toggle('open',open)});
  const route=[[8.0883,77.5385],[9.9252,78.1198],[11.6643,78.146],[12.9716,77.5946],[18.5204,73.8567],[19.076,72.8777],[23.2599,77.4126],[26.9124,75.7873],[28.6139,77.209],[32.7266,74.857],[34.0837,74.7973]];
  const map=L.map('expeditionMap',{zoomControl:false,attributionControl:true,scrollWheelZoom:false}).setView([22.7,79],5);
  L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19,attribution:'© OpenStreetMap © CARTO'}).addTo(map);
  L.polyline(route,{color:'#a7aaa8',weight:3,dashArray:'4 9',opacity:.8}).addTo(map);
  L.circleMarker(route[0],{radius:6,color:'#f4f1e9',weight:2,fillColor:'#e54a2a',fillOpacity:1}).addTo(map).bindTooltip('Kanyakumari · Start');
  L.circleMarker(route.at(-1),{radius:6,color:'#f4f1e9',weight:2,fillColor:'#e54a2a',fillOpacity:1}).addTo(map).bindTooltip('Kashmir · Finish');
  const current=L.circleMarker([26.8467,80.9462],{radius:9,color:'#f4f1e9',weight:3,fillColor:'#64b94f',fillOpacity:1}).addTo(map);
  let currentPoint=[26.8467,80.9462];$('mapLocate').addEventListener('click',()=>map.flyTo(currentPoint,9));
  function render(data){const live=data.mode==='live';const total=Number(data.distanceTotal)||0,target=Number(data.targetDistance)||4000,progress=Math.min(100,total/target*100);document.body.dataset.mode=live?'live':'preparation';text('headerStatus',live?'LIVE WALK':'PREPARATION');text('mapMode',live?'LIVE WALKING':'PREPARATION MODE');text('dayNumber',live?fmt(data.day):'—');text('dayLabel',live?'Expedition day':'Before start');text('totalDistance',fmt(total));text('targetDistance',fmt(target));text('completion',`${progress.toFixed(1)}%`);$('completionBar').style.width=`${progress}%`;text('todayDistance',fmt(data.distanceToday));text('walkingTime',`${fmt(data.walkingMinutes)} min walking`);text('fieldStatus',data.status||'Preparing');text('steps',fmt(data.stepsToday));text('weather',data.temperature==null?'Awaiting data':`${data.temperature}°C`);text('altitude',data.altitude==null?'—':`${fmt(data.altitude)} m`);text('connectivity',data.connectivity||'Unknown');text('nextStop',data.nextPlace||'The road decides');text('nextEta',data.nextPlaceEta||'Estimate pending');text('lastSleep',data.lastSleep||'Not shared');text('battery',data.battery==null?'—':`${data.battery}%`);text('latestTitle',data.latestTitle||'Latest dispatch');text('latestText',data.latestText||'The next field signal will appear here.');text('dispatchPlace',`${data.currentPlace||'ON THE ROAD'} · ${live?'FIELD DISPATCH':'PREPARATION'}`.toUpperCase());$('latestLink').href=data.latestUrl||'journal.html';text('partnerName',data.sponsorName||'Partnership open');$('partnerLink').href=data.sponsorUrl||'sponsorship.html';text('journeyLine',live?`Day ${fmt(data.day)} · ${fmt(data.distanceToday)} km today`:'Preparing to walk India from south to north.');}
  function renderLocation(loc){currentPoint=[loc.lat,loc.lon];current.setLatLng(currentPoint);const live=loc.source==='live-gps';const age=loc.updatedAt?Math.max(0,Math.round((Date.now()-new Date(loc.updatedAt))/1000)):null;text('currentPlace',live?'LIVE GPS\nPOSITION':'Lucknow,\nUttar Pradesh');$('currentPlace').innerHTML=(live?'Live GPS<br>position':'Lucknow,<br>Uttar Pradesh');text('mapUpdated',loc.updatedAt?(age<90?'Updated just now':`${Math.floor(age/60)} min since last signal`):'Live GPS begins on day one');text('lastGps',loc.updatedAt?(age<90?'Just now':`${Math.floor(age/60)} min ago`):'Not started');if(live)map.panTo(currentPoint);}
  async function refresh(){render(fallback);try{const [journey,location]=await Promise.all([fetch('/api/journey',{cache:'no-store'}),fetch('/api/location',{cache:'no-store'})]);if(journey.ok)render({...fallback,...await journey.json()});if(location.ok)renderLocation(await location.json())}catch{}setTimeout(()=>map.invalidateSize(),100)}
  renderLocation({lat:26.8467,lon:80.9462,source:'preparation-marker',updatedAt:null});refresh();setInterval(refresh,60000);
})();
